In [2]:
import tensorflow as tf

In [2]:
'''keras and tf version check'''
tf.__version__


'2.3.0'

In [3]:
tf.keras.__version__

'2.4.0'

KERAS SEQUENTIAL MODEL

BUILD-- write code
COMPILE--execute code
FIT--train model
EVALUTATE--compute loss,accuracy
MAKE PREDICTIONS--make prediction for new data

In [ ]:
'''dice simple project'''

In [13]:
tf.random.set_seed=5

In [26]:
tf.random.set_seed=11
dice1=tf.Variable(tf.random.uniform([10,1],minval=1,maxval=7,dtype=tf.int32,seed=7))
dice1

<tf.Variable 'Variable:0' shape=(10, 1) dtype=int32, numpy=
array([[4],
       [2],
       [2],
       [5],
       [5],
       [6],
       [1],
       [4],
       [3],
       [2]])>

In [27]:
tf.random.set_seed=11
dice2=tf.Variable(tf.random.uniform([10,1],minval=1,maxval=7,dtype=tf.int32,seed=7))
dice2

<tf.Variable 'Variable:0' shape=(10, 1) dtype=int32, numpy=
array([[6],
       [5],
       [2],
       [4],
       [1],
       [5],
       [2],
       [4],
       [6],
       [1]])>

In [29]:
#new matrix having dice1 outcome dice2 outcome and summation of both outcomes
new_matrix=tf.concat([dice1,dice2,dice1+dice2],axis=1)

In [30]:
new_matrix.numpy()

array([[ 4,  6, 10],
       [ 2,  5,  7],
       [ 2,  2,  4],
       [ 5,  4,  9],
       [ 5,  1,  6],
       [ 6,  5, 11],
       [ 1,  2,  3],
       [ 4,  4,  8],
       [ 3,  6,  9],
       [ 2,  1,  3]])

In [31]:
print(new_matrix)

tf.Tensor(
[[ 4  6 10]
 [ 2  5  7]
 [ 2  2  4]
 [ 5  4  9]
 [ 5  1  6]
 [ 6  5 11]
 [ 1  2  3]
 [ 4  4  8]
 [ 3  6  9]
 [ 2  1  3]], shape=(10, 3), dtype=int32)


In [ ]:
'''KERAS SEQUENTIAL MODEL'''

In [32]:
mnist_data=tf.keras.datasets.mnist

In [35]:
mnist_data

<module 'tensorflow.keras.datasets.mnist' from 'c:\\users\\madhusudan\\anaconda3\\envs\\project1\\lib\\site-packages\\tensorflow\\keras\\datasets\\mnist\\__init__.py'>

In [37]:
'''loading test and train data '''
(train_x,train_y),(test_x,test_y)=mnist_data.load_data()

In [41]:
'''data check'''
'''numbers from 0 to 9 in output'''
print(test_y)
train_y

[7 2 1 ... 4 5 6]


array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [60]:
#defining variables
epoch=5
batch_size=32

In [43]:
'''normalizing data means converitng to float  data type of tensor type'''
#dividing by 255 coz color is there RGB value is 255 or we can say converting colored image to greyscale
train_x,test_x=tf.cast(train_x/255.0,tf.float32),tf.cast(test_x/255.0,tf.int32)
#normalizing means converitng to tensors
train_y,test_y=tf.cast(train_y,tf.int64),tf.cast(test_y,tf.int64)

In [44]:
'''testing on 10000 datas'''
'''training on 60000 datas of 0to9 value'''
#total 70000 data
print(test_y)
train_y

tf.Tensor([7 2 1 ... 4 5 6], shape=(10000,), dtype=int64)


<tf.Tensor: shape=(60000,), dtype=int64, numpy=array([5, 0, 4, ..., 5, 6, 8], dtype=int64)>

In [50]:
#building the model
mnistmodel1=tf.keras.models.Sequential([
tf.keras.layers.Flatten(),
tf.keras.layers.Dense(512,activation=tf.nn.relu),
tf.keras.layers.Dropout(0.2),
tf.keras.layers.Dense(10,activation=tf.nn.softmax)
])

In [52]:
optimisers=tf.keras.optimizers.Adam()

In [54]:
#compiling the model
mnistmodel1.compile(optimisers,'sparse_categorical_crossentropy',['accuracy'])

Fitting the model

In [61]:
#training my model for 20 epochsand batch of 16... randomly selected epoch and batch
mnistmodel1.fit(train_x,train_y,batch_size,epoch)

Epoch 1/5
1875/1875 [==============================] - 15s 8ms/step - loss: 1.7305 - accuracy: 0.3898
Epoch 2/5
1875/1875 [==============================] - 15s 8ms/step - loss: 1.5757 - accuracy: 0.4313
Epoch 3/5
1875/1875 [==============================] - 13s 7ms/step - loss: 1.5310 - accuracy: 0.4436
Epoch 4/5
1875/1875 [==============================] - 16s 9ms/step - loss: 1.5022 - accuracy: 0.4521
Epoch 5/5
1875/1875 [==============================] - 15s 8ms/step - loss: 1.4800 - accuracy: 0.4589


Evalutating the model

In [62]:
mnistmodel1.evaluate(test_x,test_y)

313/313 [==============================] - 2s 8ms/step - loss: 1.5942 - accuracy: 0.4283


[1.59417724609375, 0.42829999327659607]

'''alternative way to create a mdoel'''
The alternative to passing a list of layers to the Sequential model's constructor is to use the add method, as follows, for the same architecture:


In [ ]:
'''building model and compiling'''

In [57]:
mnistmodel2 = tf.keras.models.Sequential();
mnistmodel2.add(tf.keras.layers.Flatten())
mnistmodel2.add(tf.keras.layers.Dense(512, activation='relu'))
mnistmodel2.add(tf.keras.layers.Dropout(0.2))
mnistmodel2.add(tf.keras.layers.Dense(10,activation=tf.nn.softmax))
mnistmodel2.compile (optimizer= tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy',metrics = ['accuracy'])

In [ ]:
'''fitting the model'''

In [58]:
mnistmodel2.fit(train_x,train_y,128,5)

Epoch 1/5
469/469 [==============================] - 9s 19ms/step - loss: 0.2836 - accuracy: 0.9190
Epoch 2/5
469/469 [==============================] - 7s 15ms/step - loss: 0.1206 - accuracy: 0.9647
Epoch 3/5
469/469 [==============================] - 8s 17ms/step - loss: 0.0835 - accuracy: 0.9760
Epoch 4/5
469/469 [==============================] - 8s 17ms/step - loss: 0.0637 - accuracy: 0.9808 0s -
Epoch 5/5
469/469 [==============================] - 7s 15ms/step - loss: 0.0503 - accuracy: 0.9849


In [59]:
'''evalutiang the model'''
mnistmodel2.evaluate(test_x,test_y)


313/313 [==============================] - 3s 8ms/step - loss: 2.1739 - accuracy: 0.1749


[2.173877477645874, 0.17489999532699585]

In [ ]:
KERAS FUNCTIONAL API

The functional API lets you build much more complex architectures than the simple linear stack of Sequential models we have seen previously.
It also supports more advanced models. 
These models include multi-input and multi-output models, models with shared layers, and models with residual connections.

In [63]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist
(train_x,train_y), (test_x, test_y) = mnist.load_data()
train_x, test_x = train_x/255.0, test_x/255.0
epochs=10


In [64]:
'''creating a model'''
inputs = tf.keras.Input(shape=(28,28)) # Returns a 'placeholder' tensor
x = tf.keras.layers.Flatten()(inputs)
x = tf.keras.layers.Dense(512, activation='relu',name='d1')(x)
x = tf.keras.layers.Dropout(0.2)(x)
predictions = tf.keras.layers.Dense(10,activation=tf.nn.softmax, name='d2')(x)
mnistmodel3 = tf.keras.Model(inputs=inputs, outputs=predictions)

In [65]:
'''compiling and training the model'''
optimiser = tf.keras.optimizers.Adam()
mnistmodel3.compile (optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
mnistmodel3.fit(train_x, train_y, batch_size=32, epochs=epochs)

Epoch 1/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.2207 - accuracy: 0.9345
Epoch 2/10
1875/1875 [==============================] - 13s 7ms/step - loss: 0.0970 - accuracy: 0.9705
Epoch 3/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0688 - accuracy: 0.9783
Epoch 4/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0525 - accuracy: 0.9830
Epoch 5/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0431 - accuracy: 0.9858
Epoch 6/10
1875/1875 [==============================] - 14s 7ms/step - loss: 0.0358 - accuracy: 0.9884
Epoch 7/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0320 - accuracy: 0.9893
Epoch 8/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0279 - accuracy: 0.9901
Epoch 9/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0251 - accuracy: 0.9918
Epoch 10/10
1875/1875 [==============================] - 15s 8ms/step - l

In [ ]:
'''evaluating the model'''
mnistmodel3.evaluate(test_x, test_y)

In [73]:
import numpy as np

In [74]:
np.unique(test_y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)